#include <iostream>
using namespace std;

int main(){
	int HARGA_POKOK, JUMLAH_CICILAN, JANGKA_WAKTU, BUNGA, KEUNTUNGAN_PENJUAL, HARGA_MOTOR, TOTAL_PENGELUARAN;
	cout <<"\tMENGHITUNG CICILAN PEMBELIAN SEPEDA MOTOR"<<endl;
	cout <<"HARGA MOTOR : Rp. ";cin>>HARGA_MOTOR;
	cout <<"JANGKA WAKTU CICILAN (BULAN) : ";cin>>JANGKA_WAKTU;
	
	cout <<"RINCIAN BIAYA DAN KEUNTUNGAN"<<endl;
	
	HARGA_POKOK=HARGA_MOTOR/JANGKA_WAKTU;
	BUNGA=HARGA_POKOK*0.1;
	JUMLAH_CICILAN=HARGA_POKOK+BUNGA;
	TOTAL_PENGELUARAN=JUMLAH_CICILAN*JANGKA_WAKTU;
	KEUNTUNGAN_PENJUAL=TOTAL_PENGELUARAN-HARGA_MOTOR;
	
	cout <<"\nCICILAN PERBULAN : Rp. "<<JUMLAH_CICILAN;
	
	cout <<"\nTOTAL PENGELUARAN : Rp. "<<TOTAL_PENGELUARAN;
	
	cout <<"\nKEUNTUNGAN PENJUAL : Rp. "<<KEUNTUNGAN_PENJUAL;
	
	return 0;
}
