#include<iostream>
using namespace std;

int main(){
	float NILAI_PRAKTIKUM,NILAI_TEORI,NILAI_TUGAS_DAN_FINAL_PROJECT,RATA_RATA;
	cout <<"MENGHITUNG NIALI RATA RATA DARI MATA KULIAH PEMROGAMAN TERSTRUKTUR"<<endl;
	cout <<"MASUKKAN NILAI PRAKTIKUM = ";cin>>NILAI_PRAKTIKUM;
	cout <<"MASUKKAN NILAI TEORI"
	;cout <<"MASUKKAN NILAI TUGAS DAN FINAL PROJECT = ";cin>>NILAI_TUGAS_DAN_FINAL_PROJECT;
	RATA_RATA = (NILAI_PRAKTIKUM*40/100)+(NILAI_TEORI*40/100)+(NILAI_TUGAS_DAN_FINAL_PROJECT*20/100);
	cout <<"RATA RATA = "<<RATA_RATA<<endl;
}
